### PR TITLE
Start testing PHP 7.4 on travis

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
The PHP 7.4 test is failing right now, because of xdebug is missing. Need to investigate.

**Comment by reedy** [comment]
Looks to be an upstream issue https://travis-ci.community/t/cannot-disable-xdebug-on-php-7-4/6308

**Comment by NielsLeenheer** [comment]
Ah, thanks!

Let's just wait a few days before applying this PR then.

**Comment by reedy** [comment]
> Ah, thanks!
> 
> Let's just wait a few days before applying this PR then.

Seems sensible. We could mark it as an "allowed failure" but as there's no real rush, there doesn't seem much benefit to doing that, as it just needs reverting later

**Comment by NielsLeenheer** [comment]
Problem seems fixed now. Merging.

**Pull request merged**
