### PR TITLE
Rocket Chat (in-App) Web Browser (uses Electron)

### PR DESCRIPTION
**Pull request by summercms**
Rocket Chat (in-App) Web Browser - https://github.com/WhichBrowser/Parser-PHP/issues/221

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
There is something not right with this detection. It says it is running on iPhone and using Electron. There is no Electron for iPhone.

**Comment by ayumi-cloud** [comment]
@NielsLeenheer 

This seems correct to me.

The `Rocket Chat` app seems to be coded using `Electron` see the following links as proof:

- [Rocket.Chat.Electron](https://github.com/RocketChat/Rocket.Chat.Electron)

- [List of apps running Electron](https://www.electronjs.org/apps/rocket-chat)

The results say the following:

```
Rocket Chat 2.9.0 on an Apple iPhone running iOS 8.1.2
```

Lastly the `Rocket Chat` app that's built using `Electron` is on the following app stores:

- https://apps.apple.com/us/app/rocket-chat/id1148741252

- https://play.google.com/store/apps/details?id=chat.rocket.android&hl=en

Let me know if I've missed something here - but it seems correct to me.

**Comment by NielsLeenheer** [comment]
The desktop version is indeed build using Electron. But the mobile version is not. Electron only supports Mac, Linux or Windows. Not mobile operating systems.  

```
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B440 Rocket.Chat+/2.9.0 Chrome/58.0.3029.110 Electron/1.7.6 Safari/537.36
```

The thing is that the UA string says that is build with Electron and running Chrome. And at the same time it running on an iPhone. That is not possible. 

So this is either:
a) the desktop version that lies about running on an iPhone
b) the mobile version that lies about using Electron.

**Comment by ayumi-cloud** [comment]
Did some digging could only find three different UA types:

### Linux

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat+/2.9.0 Chrome/58.0.3029.110 Electron/1.7.6 Safari/537.36
```

### Windows

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/2.17.7 Chrome/78.0.3904.130 Electron/7.1.10 Safari/537.36
```

### MAC

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/2.17.11 Chrome/78.0.3904.130 Electron/7.1.14 Safari/537.36
```

Couldn't find an iPhone one.

~Will add these three UA's as tests.

**Comment by ayumi-cloud** [comment]
2 tests failing out of 3.

Saying:

```
Electron 7.1.10 on Windows 10

User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/2.17.7 Chrome/78.0.3904.130 Electron/7.1.10 Safari/537.36
```

and

```
Electron 7.1.14 on macOS High Sierra 10.13

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/2.17.11 Chrome/78.0.3904.130 Electron/7.1.14 Safari/537.36
```

Maybe need to add custom code to the file: https://github.com/WhichBrowser/Parser-PHP/blob/master/src/Analyser/Header/Useragent/Application.php

Will continue this pr later and continue with the other pr's for now...

**Comment by ayumi-cloud** [comment]
@NielsLeenheer Please can you merge this pr.

**Pull request closed without merging**
