### PR TITLE
Add `Go Http Client` a very popular bot

### PR DESCRIPTION
**Pull request by ayumi-cloud**
UA Examples:

User   agent | Version | Popularity
--|--|--
Go-http-client/1.1   | 1.1 | Very common
Go-http-client/2.0   | 2 | Common
Go-http-client/1.1   https://hstspreload.org/ checker; see https://sapphire.alexcohn.com/hsts.html   | 1.1 | Uncommon
Go-http-client/1.1   | 1.1 | Uncommon
Mozilla/5.0   (compatible; Go-http-client/1.1; +aaa@bbb.com) | 1.1 | Uncommon
go-httpclient   v0.5.1 | 0.5 | Uncommon
Go-http-client/1.1   | 1.1 | Uncommon
Go-http-client/1.2   | 1.2 | Uncommon
Go-http-client/1.1   - [handyCafe Filter/3.3.16] | 1.1 | Uncommon

PR adds two test cases.

Link to this repo tests: http://thadafinser.github.io/UserAgentParserComparison/v5/user-agent-detail/fa/0e/fa0e85a4-0f6f-4c13-b573-9d14c87cc2e2.html#modal-47a9cd06-e213-4882-bc34-db6aed664223

### CODE REVIEW

**Comment by ayumi-cloud** [comment]
not finished yet - still working on this

**Comment by ayumi-cloud** [comment]
Fatal error: Uncaught Error: Call to a member function toArray() on string in /home/travis/build/WhichBrowser/Parser-PHP/src/Model/Browser.php:168

**Comment by ayumi-cloud** [comment]
PHP Fatal error:  Uncaught Error: Call to a member function toArray() on string in /home/travis/build/WhichBrowser/Parser-PHP/src/Model/Browser.php:168

**Comment by ayumi-cloud** [comment]
Stuck on this - not sure what the issue is going on? Any suggestions from anyone would be helpful.

**Comment by mariotsi** [comment]
Does not happen locally?

**Comment by ayumi-cloud** [comment]
@NielsLeenheer @mariotsi

> Does not happen locally?

Just tested it locally and same thing happens, the repo seems to not like adding a custom bot code into the file: 

`src/Analyser/Header/Useragent/Bot.php`

**Comment by ayumi-cloud** [comment]
Found the solution now!

**Comment by NielsLeenheer** [comment]
Fixed by efffe033df41eb448cf76faa2e7deeb05649211c

**Pull request closed without merging**
