### PR TITLE
Sputnik Browser

### PR DESCRIPTION
**Pull request by ayumi-cloud**
Sputnik Browser - https://github.com/WhichBrowser/Parser-PHP/issues/189

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
Could you add testcases for both UA string variants?

**Comment by ayumi-cloud** [comment]
@NielsLeenheer Please can you post the other UA in the comments and I will update the pr for you. (Looking at the issue #189 - I could only see one type of UA for this browser).

**Comment by NielsLeenheer** [comment]
I was assuming you had an alternative UA string that matches the regex below:

```php
        [ 'name' => 'Sputnik',              'id'    => 'sputnik',     'regexp' => '/Sputnik\/([0-9.]*)/iu', 'details' => 3 ],
```

I'll see if I can find one.

**Comment by ayumi-cloud** [comment]
```php
[
    'name'   => 'Sputnik',
    'id'         => 'sputnik',
    'regexp' => '/Sputnik\/([0-9.]*)/iu',
    'details' => 3
],
```



Mozilla/5.0 (compatible; SputnikFaviconBot/1.2; +http://corp.sputnik.ru/webmaster)
Mozilla/5.0 (compatible; SputnikBot/2.3; +http://corp.sputnik.ru/webmaster)
https://udger.com/resources/ua-list/bot-detail?bot=SputnikBot


temp comment

**Comment by ayumi-cloud** [comment]
@NielsLeenheer 

Done some research and checked their website and other UA repo's. It seems like `Sputnik\/([0-9.]*)` doesn't exist and everyone only uses `/SputnikBrowser\/([0-9.]*)/` also the browser has a mobile and desktop version. Couldn't find a mobile UA for the browser to add to the test section though and I don't really want to download and add the app to my phone to find it though.

Anyway removed 2nd regex and made the browser mobile and desktop. So hopefully everything ok and you can merge this now.

**Pull request merged**
