### PR TITLE
Add `Blogger` social media platform

### PR DESCRIPTION
**Pull request by ayumi-cloud**
See Github Issue: https://github.com/WhichBrowser/Parser-PHP/issues/505

Link: https://www.blogger.com/

### CODE REVIEW

**Comment by ayumi-cloud** [comment]
@NielsLeenheer Please can you merge this pr.

**Comment by notcher-dev** [comment]
https://redroom15.blogspot.com/?m=1

**Comment by ayumi-cloud** [comment]
See new issue: https://github.com/WhichBrowser/Parser-PHP/issues/558

**Comment by NielsLeenheer** [comment]
Fixed in e0f60181ac7e885977feee5ac83a911379505031

**Pull request closed without merging**
