### PR TITLE
ICE Browser

### PR DESCRIPTION
**Pull request by summercms**
ICE Browser - https://github.com/WhichBrowser/Parser-PHP/issues/229

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
Could you also add test coverage for the following UA strings?

```
ICE Browser/5.05 (Java 1.4.0; Windows 2000 5.0 x86)
ICE Browser/v5_4_3 (Java 1.4.2; Windows XP 5.1 x86)
```

**Comment by ayumi-cloud** [comment]
~Need to work on this tomorrow, regex not correct so far

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
.........and so on!

Because it's using too many php packages at once!

**Comment by ayumi-cloud** [comment]
yet again:

image

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
@NielsLeenheer Please can you merge this pr.

**Pull request closed without merging**
