### PR TITLE
Add `Gmail Image Proxy` to email apps

### PR DESCRIPTION
**Pull request by summercms**
> I feel kind and thought I'd write this pr for someone else's github issue.

See their github issue here: https://github.com/WhichBrowser/Parser-PHP/issues/127

More info: https://www.scientiamobile.com/what-is-google-image-proxy/

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
There is something to say for adding Google Image Proxy as an application named "Gmail". But in that case we should not use the application list, but do the detection in PHP, because we do need to reset the operating system. 

Even though the user agent string says Windows XP, the actual bot does not run on Windows XP. And neither does the user of Gmail run Windows XP on their own machine.

**Comment by ayumi-cloud** [comment]
@NielsLeenheer 

So you're suggesting.

Changing this:

```
result: { browser: { name: 'Gmail Image Proxy', family: { name: Firefox, version: '11.0' }, type: 'app:email' }, engine: { name: Gecko, version: '11.0' }, os: { name: Windows, version: { value: '5.1', alias: XP } }, device: { type: desktop } }
```

into something like this:

```
result: { browser: { name: 'Gmail Image Proxy', type: 'app:email' }, device: { type: proxy } }
```

**Comment by summercms** [comment]
Therefore `Application.php`

```
        /* Gmail Image Proxy */

        if (preg_match('/GoogleImageProxy/u', $ua, $match)) {
            $this->data->browser->name = 'Gmail Image Proxy';
            $this->data->browser->mode = 'proxy';
            $this->data->browser->type = Constants\BrowserType::APP_EMAIL;
            $this->data->os->reset();
            $this->data->engine->reset();
            $this->data->device->reset();
        }
```

**Comment by summercms** [comment]
Therefore `Application.php`

```
        /* Gmail Image Proxy */

        if (preg_match('/GoogleImageProxy/u', $ua, $match)) {
            $this->data->browser->reset();
            $this->data->browser->name = 'Gmail Image Proxy';
            $this->data->browser->version = null;
            $this->data->browser->type = Constants\BrowserType::APP_EMAIL;
            $this->data->os->reset();
            $this->data->engine->reset();
            $this->data->device->reset();
        }
```

Results:

```
    headers: 'User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)'
    readable: 'Gmail Image Proxy'
    result:  { browser: { name: 'Gmail Image Proxy', type: 'app:email' }, engine: { name: Gecko, version: '11.0' } }
```

**Comment by summercms** [comment]
cleaned version: https://github.com/summercms/Parser-PHP-v3.x.x/pull/178/files

**Pull request closed without merging**
