### PR TITLE
Baidu Spark Browser (Not being found - updating the code and adding more regex)

### PR DESCRIPTION
**Pull request by summercms**
Baidu Spark Browser - https://github.com/WhichBrowser/Parser-PHP/issues/210

---

Not being found as the browser uses Chrome and also missing some regex.

### CODE REVIEW

**Comment by ayumi-cloud** [comment]
Package not finding anything! 

e.g.

User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.31 (KHTML, like Gecko) Spark/2.x Chrome/26.0.1410.43 Safari/537.31

Shows this:

Chrome 26 on Windows 8

**Comment by NielsLeenheer** [comment]
Could you also add a test case for a UA that contain `Spark/fzz` so that we can be absolutely sure that any future changes will not cause it to be detected as Baidu Spark.

**Comment by ayumi-cloud** [comment]
```
User-Agent: Mozilla/5.0 (Linux; U; Android/2.1.0 ; xx) AppleWebKit/533.1 Spark/fzz Safari/533.1 Version/4.0 Pre/1.0
```

and

```
User-Agent: Mozilla/5.0 (Linux; U; Android/2.1.0 ; xx) AppleWebKit/533.1 Spark/fzz Safari/533.1 Version/4.0 Pre/1.1; Mobile; AppleWebKit/533.1; Android2.3.7; Android; Version/4.0; Safari/533.1
```

To add.

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
@NielsLeenheer Please can you merge this pr.

**Comment by summercms** [comment]
cleaned version: https://github.com/summercms/Parser-PHP-v3.x.x/pull/193/files

**Pull request closed without merging**
