### PR TITLE
webOS Browser version not detected - updated code to detect version numbers

### PR DESCRIPTION
**Pull request by summercms**
- [x] webOS incomplete code that doesn't detect browser version - https://github.com/WhichBrowser/Parser-PHP/issues/187

### Before

```
webOS Browser on an emulator running webOS 2.0
```

### After

```
webOS Browser 234.83 on an emulator running webOS 2.0
```

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
I'm not sure this is actually a version number of the browser.

**Comment by ayumi-cloud** [comment]
You're correct this is not correct have done some more research and found that the `hpwOS` part gives the version number e.g.

```
Mozilla/5.0 (hp-tablet; Linux; hpwOS/3.0.5; U; en-US) AppleWebKit/534.6 (KHTML, like Gecko) wOSBrowser/234.83 Safari/534.6 TouchPad/1.0
```

Take the `hpwOS/3.0.5` gives the following results:

```
Browser Name: 'webOS Browser',
Browser Version: '3.0.5',

Will update the code.

**Comment by ayumi-cloud** [comment]
@NielsLeenheer Please can you merge this pr.

**Comment by summercms** [comment]
closing this pr, opening new issue here: https://github.com/WhichBrowser/Parser-PHP/issues/661

**Pull request closed without merging**
