### PR TITLE
Alienforce Browser

### PR DESCRIPTION
**Pull request by summercms**
Alienforce Browser - https://github.com/WhichBrowser/Parser-PHP/issues/208

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
Could you also add a testcase for:
`Mozilla/5.0 (Windows NT 6.1; rv:9.0.1) Gecko/20100101 Firefox/9.0.1 Alienforce3.0/9.0.1`

**Comment by ayumi-cloud** [comment]
> Could you also add a testcase for: Mozilla/5.0 (Windows NT 6.1; rv:9.0.1) Gecko/20100101 Firefox/9.0.1 Alienforce3.0/9.0.1

Have tested it and shows: `Firefox 9.0.1 on Windows 7`

Going to add some custom code in the: https://github.com/WhichBrowser/Parser-PHP/blob/master/src/Analyser/Header/Useragent/Browser.php

To see if I can over-write the default `Firefox` setting.

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
@NielsLeenheer Please can you merge this pr.

**Pull request closed without merging**
