### PR TITLE
`Fluid App` and `Fluid Browser` not detected

### PR DESCRIPTION
**Pull request by summercms**
Fluid Browser - https://github.com/WhichBrowser/Parser-PHP/issues/154

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
There seems to be 3 or 4 unrelated browsers named Fluid on Mac and Android. Need to look at this a bit closer.

**Comment by ayumi-cloud** [comment]
### Browser 1

Fluid (on MAC - Desktop only):
https://en.wikipedia.org/wiki/Fluid_(web_browser)
https://fluidapp.com/

### Browser 2

Fluid (on MAC - Desktop only):
https://fluidbrowser.com/
https://apps.apple.com/us/app/fluid-browser/id1077036385?mt=12
https://chrome.google.com/webstore/detail/fluid-browser/lbechkjecpoldpfdbikjnabefdjahaok?hl=en

(*) Both seems to not be for Android or PC.

**Comment by summercms** [comment]
I can't see a problem here! 

- There are two different browsers with the exact same name! 
- Browser 1 was created before browser 2. 
- Browser 2 has been removed from chrome store - probably containing malware! 
- Browser seems to be clean: https://www.virustotal.com/gui/file/cf58c480f631d2adc050b423e65776e253f52989ade9c1aaf8d77b8ced63a653/detection

This repo discovers both user agents (for historical purposes).

### Browser 1

Fluid (on MAC - Desktop only):
https://en.wikipedia.org/wiki/Fluid_(web_browser)
https://fluidapp.com/
https://fluidapp.com/changelog.html

### Browser 2

Fluid (on MAC - Desktop only):
https://fluidbrowser.com/
https://apps.apple.com/us/app/fluid-browser/id1077036385?mt=12 (can't access this web page)
https://chrome.google.com/webstore/detail/fluid-browser/lbechkjecpoldpfdbikjnabefdjahaok?hl=en (removed from Chrome Store)

**Comment by summercms** [comment]
- There are two different browsers with the exact same name! 
- Browser 1 was created before browser 2. 
- Browser 2 has been removed from chrome store - probably containing malware! 
- Browser 1 seems to be clean: https://www.virustotal.com/gui/file/cf58c480f631d2adc050b423e65776e253f52989ade9c1aaf8d77b8ced63a653/detection

Will adjust the names as below:

### Browser 1 (Fluid App)

Fluid (on MAC - Desktop only):
https://en.wikipedia.org/wiki/Fluid_(web_browser)
https://fluidapp.com/
https://fluidapp.com/changelog.html

### Browser 2 (Fluid Browser)

Fluid (on MAC - Desktop only):
https://fluidbrowser.com/
https://apps.apple.com/us/app/fluid-browser/id1077036385?mt=12 (can't access this web page)
https://chrome.google.com/webstore/detail/fluid-browser/lbechkjecpoldpfdbikjnabefdjahaok?hl=en (removed from Chrome Store)

**Comment by summercms** [comment]
- There are two different browsers with the exact same name! 
- Browser 1 was created before browser 2. 
- Browser 2 has been removed from chrome store - probably containing malware! 
- Browser 1 seems to be clean: https://www.virustotal.com/gui/file/cf58c480f631d2adc050b423e65776e253f52989ade9c1aaf8d77b8ced63a653/detection

Will adjust the names as below:

### Browser 1 (Fluid App)

Fluid (on MAC - Desktop only):
https://en.wikipedia.org/wiki/Fluid_(web_browser)
https://fluidapp.com/
https://fluidapp.com/changelog.html

User agent | Version | OS | Hardware Type | Popularity
-- | -- | -- | -- | --
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) FluidApp Version/2249 Safari/601.3.9 | 2.2 | Mac OS X | Computer | Uncommon
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/1601.7.8 (KHTML, like Gecko) FluidApp Version/1842 Safari/1601.7.8 | 1.8 | Mac OS X | Computer | Uncommon
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/534.57.7 (KHTML, like Gecko) FluidApp Version/1920 Safari/534.57.7 | 1.9 | Mac OS X | Computer | Uncommon
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/534.57.7 (KHTML, like Gecko) FluidApp Version/2155 Safari/534.57.7 | 2.1 | Mac OS X | Computer | Uncommon
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/1601.4.4 (KHTML, like Gecko) FluidApp Version/1842 Safari/1601.4.4 | 1.8 | Mac OS X | Computer | Uncommon
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.74.9 (KHTML, like Gecko) FluidApp Version/1842 Safari/537.74.9 | 1.8 | Mac OS X | Computer | Uncommon

UA:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) FluidApp Version/2249 Safari/601.3.9
```

### Browser 2 (Fluid Browser)

Fluid (on MAC - Desktop only):
https://fluidbrowser.com/
https://apps.apple.com/us/app/fluid-browser/id1077036385?mt=12 (can't access this web page)
https://chrome.google.com/webstore/detail/fluid-browser/lbechkjecpoldpfdbikjnabefdjahaok?hl=en (removed from Chrome Store)

UA:

```
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_6; en-us) AppleWebKit/528.16 (KHTML, like Gecko) Fluid/0.9.6 Safari/528.16
```

**Comment by summercms** [comment]
PR re-write found here: https://github.com/summercms/Parser-PHP-v3.x.x/pull/209/files

**Pull request closed without merging**
