### PR TITLE
Add `WebPageTest` to app section

### PR DESCRIPTION
**Pull request by summercms**
See github issue: https://github.com/WhichBrowser/Parser-PHP/issues/555

### CODE REVIEW

**Comment by ayumi-cloud** [comment]
Remove bot code and move to app section.

**Comment by NielsLeenheer** [comment]
I don't think we should classify WebPageTest as an application on its own. WebPageTest uses actual browsers on actual devices to load a webpage and measure loading speed. So the browser in the UA string is the browser that is being used.

**Comment by ayumi-cloud** [comment]
@NielsLeenheer 

> WebPageTest uses actual browsers on actual devices to load a webpage and measure loading speed.

Yes, correct - BUT its adding the `PTST/200730.210757` to the user agent which is an **unique identifier** so makes sense to add this.

**Comment by summercms** [comment]
Therefore change `family` into `using`

Old:

```
    headers: 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 PTST 200730.21064'
    readable: 'WebPageTest 200730.21064 on Linux'
    result: { browser: { name: WebPageTest, family: { name: Chrome, version: 84 }, version: '200730.21064', type: app }, engine: { name: Blink }, os: { name: Linux }, device: { type: desktop } }
```

Into:

```
    headers: 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 PTST 200730.21064'
    readable: 'WebPageTest 200730.21064 on Linux'
    result: { browser: { name: WebPageTest, using: { name: Chrome, version: 84 }, version: '200730.21064', type: app }, engine: { name: Blink }, os: { name: Linux }, device: { type: desktop } }
```

Code to be moved in php section as well.

**Comment by summercms** [comment]
Cleaned version: https://github.com/summercms/Parser-PHP-v3.x.x/pull/179/files

**Pull request closed without merging**
