### PR TITLE
Add psr/cache 2.0 and 3.0 compatibility

### PR DESCRIPTION
**Pull request by javer**

### CODE REVIEW

**Comment by javer** [comment]
@NielsLeenheer Could you please review this PR?

**Comment by javer** [comment]
@NielsLeenheer @mariotsi Could you please review this PR with the single line of change? It will greatly help people who want to use Symfony 6. Thank you in advance.

**Comment by mariotsi** [comment]
Hello @javer, I don't handle PR on the PHP version of WhichBrowser, for that you need to wait @NielsLeenheer to review. Sorry for the wait.

**Comment by NielsLeenheer** [comment]
Thanks. Included in v2.1.3.

**Pull request closed without merging**
