### PR TITLE
Add Python's Requests library to bots list

### PR DESCRIPTION
**Pull request by filips123**
Add Python's [Requests](https://python-requests.org) library to bots list. It uses `python-requests/{package version}` user-agent.

What regex needs to be used to also detect version?
Will `/python-requests\/([0-9.]*)/u` be OK? If it will, I will edit this PR.

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
My apologies for not responding earlier. If a PR change the detection, it also need to be accompanied with tests. That way we can ensure that the change will keep working in the future.

**Comment by filips123** [comment]
Ok, I will add tests. Where it should be added?

Also, I see that some user-agents are in `data/regexes/applications-browsers.php` and related files? Should I also add Python Requests to it? How?

**Comment by NielsLeenheer** [comment]
Basically what you need to do is find some user agent strings that feature that `python-requests/` token and include them in `tests/data/bots/generic.yaml`. 

You just need to include the `headers` part. If you run `php bin/runner.php rebase` it will generate the expected results.

See the CONTRIBUTING.md file for more details.

**Comment by NielsLeenheer** [comment]
Merged, thanks!

**Pull request merged**
