### PR TITLE
Add Viber chat app to repo

### PR DESCRIPTION
**Pull request by ayumi-cloud**
Github issue: https://github.com/WhichBrowser/Parser-PHP/issues/261

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
Could you add a UA string that uses the regex `/Viber\/([0-9.]*)/u` to the testsuite?

**Comment by ayumi-cloud** [comment]
@NielsLeenheer 

Updated for 2nd review

**Comment by ayumi-cloud** [comment]
working on this still ...

**Comment by ayumi-cloud** [comment]
@NielsLeenheer 

Done.

**Pull request merged**
