### PR TITLE
Juzi Browser

### PR DESCRIPTION
**Pull request by summercms**
Juzi Browser - https://github.com/WhichBrowser/Parser-PHP/issues/161

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
Could you also add a Trident based UA string to the test suite? Maybe even a couple of different ones for different versions of Trident. For example:

```
Mozilla/5.0 (Windows NT 6.2; Trident/7.0; BOIE9;ZHCN; rv:11.0; JuziBrowser) like Gecko
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; TCO_20161009144936; JuziBrowser)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; MATP; JuziBrowser)
Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; Sicent; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; Media Center PC 6.0; JuziBrowser)
```

**Comment by ayumi-cloud** [comment]
Notes: You have changed the browser name `Juzi Browser` to `Orange Browser` but still using `juzi` as an id tag (comment for people checking in the future).

**Comment by ayumi-cloud** [comment]
@NielsLeenheer 

Done.

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
@NielsLeenheer Please can you merge this pr.

**Comment by summercms** [comment]
Closing this pr. The reason is because it's already been added in a commit found here: https://github.com/WhichBrowser/Parser-PHP/commit/c740fa0c45d61d39360f77b5614bebd29722f90e

Notes:

Juzi Browser <> Orange Browser (are same thing).

**Pull request closed without merging**
