### PR TITLE
Classilla Browser

### PR DESCRIPTION
**Pull request by summercms**
Classilla Browser - https://github.com/WhichBrowser/Parser-PHP/issues/193

---

Test results:

### Before

```
Blank
```

### After

```
Classilla Browser on Mac OS
```

### Before

```
a Nokia N90 running Series60 2.8
```

### After

```
Classilla Browser on a Nokia N90 running Series60 2.8
```

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
There seems to be something fishy going on with Classilla on S60. I believe that is the MacOS version too. Hmmm....

**Comment by ayumi-cloud** [comment]
I think that UA is wrong and going to use these two UA tests instead:

```
Mozilla/5.0 (Macintosh; U; PPC; en-US; mimic; rv:9.3.0) Gecko/20120117 Firefox/3.6.25 Classilla/CFM
Mozilla/5.0 (Macintosh; U; PPC; en-US; mimic; rv:9.3.0) Clecko/20120101 Classilla/CFM
```

**Comment by ayumi-cloud** [comment]
Going to delete the UA:

```
NokiaN90-1/3.0545.5.1 Series60/2.8 Profile/MIDP-2.0 Configuration/CLDC-1.1 (en-US; rv:9.3.0) Clecko/20120116 Classilla/CFM
```

Reading up on this browser it is a desktop based browser only and not a mobile browser to I think this UA is fake.

**Comment by ayumi-cloud** [comment]
@NielsLeenheer Please can you merge this pr.

**Comment by summercms** [comment]
cleaned version: https://github.com/summercms/Parser-PHP-v3.x.x/pull/199/files

**Pull request closed without merging**
