### PR TITLE
Adventurer Browser

### PR DESCRIPTION
**Pull request by summercms**
Adventurer Browser - https://github.com/WhichBrowser/Parser-PHP/issues/207

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
There is something weird going on the Chrome version 100 in this UA string. It appears to affect specific versions of Adventure Browser. And I don't think we should report version 100 as this might cause problems for users. I think build 2214 of Chrome is version 40 instead.

**Comment by ayumi-cloud** [comment]
Will change the test UA for this. I know that `Chrome 100` is a Chinese bot crawling the internet. Better to use a real UA. Will work on this pr tomorrow and get it correct.

**Comment by ayumi-cloud** [comment]
(I come back to this one later tests results are not correct - may create a new pr branch?)

**Comment by ayumi-cloud** [comment]
@NielsLeenheer Please can you merge this pr.

**Pull request closed without merging**
