### PR TITLE
UR Browser

### PR DESCRIPTION
**Pull request by summercms**
UR Browser - https://github.com/WhichBrowser/Parser-PHP/issues/196

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
Could you also add a testcase for `UR Browser/`, for example:
`Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Safari/537.36 Chrome/55.0.2883.87 UR Browser/51.0.2704.51`

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
image

**Comment by ayumi-cloud** [comment]
@NielsLeenheer Please can you merge this pr.

**Pull request closed without merging**
